server:
  port: 8081

spring:
  application:
    name: CUSTOMER-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_customer
    username: postgres
    password: aymen

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

keycloak:
  realm: st_realm
  auth-server-url: http://keycloak_dev:8080/auth
  resource: customer-service
  bearer-only: true
  public-client: true