server:
  port: 8082

spring:
  application:
    name: INVENTORY-SERVICE
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_inventory
    username: postgres
    password: aymen

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka